# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/x3/setup-makefiles.sh

# Bin
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/bin/ap_at_command:system/bin/ap_at_command \
  vendor/lge/x3/proprietary/bin/BCM4330B1_002.001.003.0550.0633.hcd:system/bin/BCM4330B1_002.001.003.0550.0633.hcd \
  vendor/lge/x3/proprietary/bin/bridgeutil:system/bin/bridgeutil \
  vendor/lge/x3/proprietary/bin/hdcp_test:system/bin/hdcp_test \
  vendor/lge/x3/proprietary/bin/hdmid:system/bin/hdmid \
  vendor/lge/x3/proprietary/bin/immvibed:system/bin/immvibed \
  vendor/lge/x3/proprietary/bin/init.rmnet:system/bin/init.rmnet \
  vendor/lge/x3/proprietary/bin/init.rmnet-down:system/bin/init.rmnet-down \
  vendor/lge/x3/proprietary/bin/morningcall:system/bin/morningcall \
  vendor/lge/x3/proprietary/bin/oemcrypto_api_test:system/bin/oemcrypto_api_test \
  vendor/lge/x3/proprietary/bin/rft:system/bin/rft \
  vendor/lge/x3/proprietary/bin/rft.sh:system/bin/rft.sh \
  vendor/lge/x3/proprietary/bin/rild:system/bin/rild

# Etc
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/etc/nfcee_access.xml:system/etc/nfcee_access.xml

# Firmware
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
  vendor/lge/x3/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
  vendor/lge/x3/proprietary/etc/firmware/fw_bcmdhd_mfgtest.bin:system/etc/firmware/fw_bcmdhd_mfgtest.bin \
  vendor/lge/x3/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_os_e0000000.bin:system/etc/firmware/nvavp_os_e0000000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_vid_ucode.bin:system/etc/firmware/nvavp_vid_ucode.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_h264dec2x.axf:system/etc/firmware/nvmm_h264dec2x.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_mpeg2dec.axf:system/etc/firmware/nvmm_mpeg2dec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_00001000.bin:system/etc/firmware/nvrm_avp_00001000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_0ff00000.bin:system/etc/firmware/nvrm_avp_0ff00000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_8e000000.bin:system/etc/firmware/nvrm_avp_8e000000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_9e000000.bin:system/etc/firmware/nvrm_avp_9e000000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_be000000.bin:system/etc/firmware/nvrm_avp_be000000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_e0000000.bin:system/etc/firmware/nvrm_avp_e0000000.bin \
  vendor/lge/x3/proprietary/etc/firmware/nvrm_avp_eff00000.bin:system/etc/firmware/nvrm_avp_eff00000.bin

# Lib/drm
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so

# Lib/egl
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
  vendor/lge/x3/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
  vendor/lge/x3/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
  vendor/lge/x3/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
  vendor/lge/x3/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
  vendor/lge/x3/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so

# Lib/hw
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
  vendor/lge/x3/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
  vendor/lge/x3/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
  vendor/lge/x3/proprietary/lib/hw/audio.primary.x3.so:system/lib/hw/audio.primary.x3.so \
  vendor/lge/x3/proprietary/lib/hw/audio_policy.x3.so:system/lib/hw/audio_policy.x3.so \
  vendor/lge/x3/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
  vendor/lge/x3/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
  vendor/lge/x3/proprietary/lib/hw/sensors.x3.so:system/lib/hw/sensors.x3.so

# Lib
PRODUCT_COPY_FILES += \
  vendor/lge/x3/proprietary/lib/lge_ril.so:system/lib/lge_ril.so \
  vendor/lge/x3/proprietary/lib/libami.so:system/lib/libami.so \
  vendor/lge/x3/proprietary/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
  vendor/lge/x3/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
  vendor/lge/x3/proprietary/lib/libasound.so:system/lib/libasound.so \
  vendor/lge/x3/proprietary/lib/libasound_module_rate_speexrate.so:system/lib/libasound_module_rate_speexrate.so \
  vendor/lge/x3/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
  vendor/lge/x3/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
  vendor/lge/x3/proprietary/lib/libmlFIFO.so:system/lib/libmlFIFO.so \
  vendor/lge/x3/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/lge/x3/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
  vendor/lge/x3/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
  vendor/lge/x3/proprietary/lib/libmpl_sys_jni.so:system/lib/libmpl_sys_jni.so \
  vendor/lge/x3/proprietary/lib/libnfclgeext_jni.so:system/lib/libnfclgeext_jni.so \
  vendor/lge/x3/proprietary/lib/libnvos.so:system/lib/libnvos.so \
  vendor/lge/x3/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
  vendor/lge/x3/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
  vendor/lge/x3/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
  vendor/lge/x3/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
  vendor/lge/x3/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
  vendor/lge/x3/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
  vendor/lge/x3/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
  vendor/lge/x3/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
  vendor/lge/x3/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
  vendor/lge/x3/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
  vendor/lge/x3/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
  vendor/lge/x3/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
  vendor/lge/x3/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
  vendor/lge/x3/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
  vendor/lge/x3/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
  vendor/lge/x3/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
  vendor/lge/x3/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
  vendor/lge/x3/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
  vendor/lge/x3/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
  vendor/lge/x3/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
  vendor/lge/x3/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
  vendor/lge/x3/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
  vendor/lge/x3/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
  vendor/lge/x3/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
  vendor/lge/x3/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
  vendor/lge/x3/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
  vendor/lge/x3/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
  vendor/lge/x3/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
  vendor/lge/x3/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
  vendor/lge/x3/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
  vendor/lge/x3/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
  vendor/lge/x3/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
  vendor/lge/x3/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
  vendor/lge/x3/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
  vendor/lge/x3/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
  vendor/lge/x3/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
  vendor/lge/x3/proprietary/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
  vendor/lge/x3/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
  vendor/lge/x3/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
  vendor/lge/x3/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
  vendor/lge/x3/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
  vendor/lge/x3/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
  vendor/lge/x3/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
  vendor/lge/x3/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
  vendor/lge/x3/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
  vendor/lge/x3/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
  vendor/lge/x3/proprietary/lib/libOlaLGECameraJNI.so:system/lib/libOlaLGECameraJNI.so \
  vendor/lge/x3/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/lge/x3/proprietary/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
  vendor/lge/x3/proprietary/lib/libwvdrm_L1.so:system/lib/libwvdrm_L1.so \
  vendor/lge/x3/proprietary/lib/libwvm.so:system/lib/libwvm.so \
  vendor/lge/x3/proprietary/lib/libWVStreamControlAPI_L1.so:system/lib/libWVStreamControlAPI_L1.so
